services:
  db:
    image: postgres:18.0
    container_name: ${POSTGRES_CONTAINER_NAME}
    restart: always
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/18/docker
      - ./migrations/:/docker-entrypoint-initdb.d
    networks:
      - calendorario-network

  reverse-proxy:
    image: traefik:v3.5.4
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - letsencrypt:/letsencrypt
    networks:
      - calendorario-network

  templ:
    image: ghcr.io/a-h/templ:v0.3.960
    command: generate --watch
    working_dir: /app
    volumes:
      - .:/app

  tailwindcss:
    build: ./tailwindcss
    command: -i ./tailwindcss/input.css -o ./public/tailwind.css --watch
    working_dir: /app
    tty: true
    stop_grace_period: 0s
    volumes:
      - .:/app

  app:
    image: cosmtrek/air:v1.63.0
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`localhost`)"
      - "traefik.http.services.app.loadbalancer.server.port=8080"
    restart: always
    working_dir: /app
    env_file:
      - .env
    environment:
      - GOFLAGS=-buildvcs=false
    volumes:
      - .:/app
    networks:
      - calendorario-network

volumes:
  postgres-data:
  letsencrypt:

networks:
  calendorario-network:
