services:
  reverse-proxy:
    image: traefik:v3.5.4
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - letsencrypt:/letsencrypt
    networks:
      - calendorario-network

  templ:
    image: ghcr.io/a-h/templ:v0.3.960
    command: generate -watch
    working_dir: /app
    volumes:
      - .:/app

  app:
    image: cosmtrek/air:v1.63.0
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`localhost`)"
      - "traefik.http.services.app.loadbalancer.server.port=8080"
    restart: always
    depends_on:
      - templ
    working_dir: /app
    env_file:
      - .env
    environment:
      - GOFLAGS=-buildvcs=false
    volumes:
      - .:/app
    networks:
      - calendorario-network

volumes:
  letsencrypt:

networks:
  calendorario-network:
